### PR TITLE
Return timings in iso8601 format

### PR DESCRIPTION
**Pull request by engrbm87**
## Proposed changes
Return the prayer times in `iso8601` which includes the date and timezone by setting the `iso8601` argument to True. This will be useful for getting the prayer in the correct timezone when DST happens.

### CODE REVIEW

**Comment by uchagani** [comment]
@engrbm87 let me know if you're done making updates and I can merge.

**Comment by engrbm87** [comment]
Ready to merge. 😀

**Comment by engrbm87** [comment]
Hi @uchagani , can we get this merged please.

**Comment by uchagani** [comment]
Merged, apologies for the delay. I'll try to publish a new release this evening.

**Comment by uchagani** [comment]
new version has been released: https://pypi.org/project/prayer-times-calculator/

**Comment by engrbm87** [comment]
Great, can you also make a new release on github. This is required when submitting the new version to Home Assistant. And would should other people interested in this library about the new release.

**Comment by uchagani** [comment]
@engrbm87  done.

**Pull request merged**
