### PR TITLE
Cleanup code and add type hints

### PR DESCRIPTION
**Pull request by engrbm87**
This PR cleans up the code to make it fully typed and ensure that the passed arguments are fully checked.
- Move the constants outside the class to prevent attempts to modify them as they are currently defined as class attributes.
- Update the `CalculationMethodError` exception and define a common message format.
- If calculation method "custom" is used, ensure the angles provided are `int` or `float`.
- Raise `ValueError` if the date string format doesn't match "yyyy-m-dd"
- Add docstrings and fully type the methods and variables.

Note: The type hints require python 3.10 and above. I believe its better to drop support for older python version

### CODE REVIEW

**Comment by uchagani** [comment]
@engrbm87 do you know if needing 3.10 will cause issues with Home Assistant?

**Comment by engrbm87** [comment]
HA is now on 3.11. They don't support anything older than 3.10

**Comment by engrbm87** [comment]
@uchagani , did you get the chance to review this PR.

**Comment by uchagani** [comment]
Apologies for the delay, life got in the way. I'll have this out this week.

**Comment by uchagani** [comment]
@engrbm87 thank you for doing this.  New release has been pushed:
image

**Pull request merged**
